export enum Types {
    CALCULATOR_ANNUAL_SAVINGS = 'CALCULATOR_ANNUAL_SAVINGS',
    CALCULATOR_COST_FOOD_SAVINGS = 'CALCULATOR_COST_FOOD_SAVINGS',
    CALCULATOR_FULL_TIME_EMPLOYES = 'CALCULATOR_FULL_TIME_EMPLOYES',
    CALCULATOR_INFO_LOADED = 'CALCULATOR_INFO_LOADED',
    CALCULATOR_MONTHLY_INGREDIENT_SPENDING = 'CALCULATOR_MONTHLY_INGREDIENT_SPENDING',
    TESTIMONIAL_SLIDER_LOADED = 'TESTIMONIAL_SLIDER_LOADED',
    UI_MENU_LOADED = 'UI_MENU_LOADED',
}