export enum Types {
    CALCULATOR_INFO_LOADED = 'CALCULATOR_INFO_LOADED',
    CALCULATOR_ANNUAL_SAVINGS = 'CALCULATOR_ANNUAL_SAVINGS',
    CALCULATOR_COST_FOOD_SAVINGS = 'CALCULATOR_COST_FOOD_SAVINGS',
    TESTIMONIAL_SLIDER_LOADED = 'TESTIMONIAL_SLIDER_LOADED',
    UI_MENU_LOADED = 'UI_MENU_LOADED',
}